name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "**/ARCHITECTURE.md"
      - ".github/workflows/pages.yml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Build docs
        run: make docs

      - name: Deploy Docs to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          keep_files: true # Preserve Helm index.yaml
